<?xml version="1.0" ?>
<robot name="detectiBot" xmlns:xacro="https://www.ros.org/wiki/xacro" >

<!-- =================================================================================== -->
<!-- |                                 detectiBot model                                | -->
<!-- |                             Experimental robotics lab                           | -->
<!-- =================================================================================== -->

<!-- ==================================== Xacro include ============================================ -->


 <xacro:include filename="$(find explab_2nd)/urdf/materials.xacro" />
 <xacro:include filename="$(find explab_2nd)/urdf/detectiBot.gazebo" />

<!-- ================================== Properties' list ============================================ -->
<!-- ======================== All units in m-kg-s-radians unit system =============================== -->


<!-- math and conversion  -->

  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="M_PI_2" value="1.570796327" />
  <xacro:property name="DEG_TO_RAD" value="0.017453293" />

<!-- mass  -->

  <xacro:property name="arm_link_mass" value="0.025"/>
  <xacro:property name="base_link_mass" value="0.5"/>
  <xacro:property name="gripper_link_mass" value="0.2"/> 

<!-- lenght -->

  <xacro:property name="arm_link_01_lenght" value="0.3"/>
  <xacro:property name="arm_link_02_lenght" value="0.3"/>
  <xacro:property name="arm_link_03_lenght" value="0.3"/>
  <xacro:property name="cluedo_link_lenght" value="0.3"/>
  
  <xacro:property name="err" value="-0.2"/>





<!-- ================================== Xacro definitions ========================================== -->


 <xacro:macro name="cylinder_inertia" params="mass r l"> 
    <inertia ixx="${mass*(3*r*r+l*l)/12}" ixy = "0" ixz = "0"
                iyy="${mass*(3*r*r+l*l)/12}" iyz = "0" izz="${mass*(r*r)/2}" /> 
 </xacro:macro>


    <xacro:macro name="link_wheel" params="name">
        <link name="${name}">
            <inertial>
              <mass value="0.2"/>
              <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
              <inertia ixx="0.000526666666667" ixy="0" ixz="0" iyy="0.000526666666667" iyz="0" izz="0.001"/>
            </inertial>
            <collision name="link_right_wheel_collision">
              <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
              <geometry>
                <cylinder length="0.04" radius="0.1"/>
              </geometry>
            </collision>
            <visual name="${name}_visual">
              <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
              <geometry>
                <cylinder length="0.04" radius="0.1"/>
              </geometry>
            </visual>
        </link>
    </xacro:macro>


    <xacro:macro name="joint_wheel" params="name child origin_xyz">
      <joint name="${name}" type="continuous">
        <origin rpy="0 0 0" xyz="${origin_xyz}"/>
        <child link="${child}"/>
        <parent link="base_link"/>
        <axis rpy="0 0 0" xyz="0 1 0"/>
        <limit effort="10000" velocity="1000"/>
        <joint_properties damping="1.0" friction="1.0"/>
      </joint>
    </xacro:macro>


<!-- ======================================== Link  ================================================ -->

  <link name="base_link">
    <!-- pose and inertial -->
    <pose>0 0 0.1 0 0 0</pose>
    
    <inertial>
      <mass value="${base_link_mass}"/>
      <origin rpy="0 0 0" xyz="0 0 0.1"/>
      <inertia ixx="0.0395416666667" ixy="0" ixz="0" iyy="0.106208333333" iyz="0" izz="0.106208333333"/>
    </inertial>

    <!-- chassis collision -->
    <collision name="collision_chassis">
      <geometry>
        <box size="0.5 0.3 0.07"/>
      </geometry>
    </collision>
    
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.5 0.3 0.07"/>
      </geometry>
      <material name="blue"/>
    </visual>
    
    <!-- caster front collision -->
    <collision name="caster_front_collision"> 
      <origin rpy=" 0 0 0" xyz="0.35 0 -0.05"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0</mu>
            <mu2>0</mu2>
            <slip1>1.0</slip1>
            <slip2>1.0</slip2>
          </ode>
        </friction>
      </surface>
    </collision>
    <visual name="caster_front_visual">
      <origin rpy=" 0 0 0" xyz="0.2 0 -0.05"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </visual>
  </link>
  
<!-- ==================================== Create wheels ============================================ -->


  <xacro:link_wheel name="link_right_wheel" />
  <xacro:link_wheel name="link_left_wheel" />
  <xacro:joint_wheel name="joint_right_wheel"  child="link_right_wheel"  origin_xyz="-0.05 0.15 0"  />
  <xacro:joint_wheel name="joint_left_wheel"   child="link_left_wheel"   origin_xyz="-0.05 -0.15 0"  />

<!-- ======================================== Link  ================================================ -->

   <link name="laser">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <mass value="1" />
      <xacro:cylinder_inertia mass="1" r="0.05" l="0.1" />
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="0.05" length="0.1"/>
      </geometry>
      <material name="white" />
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.1"/>
      </geometry>
    </collision>
  </link>

<!-- ======================================== Joint  =============================================== -->

  <joint name="joint_laser" type="fixed">
    <origin xyz="0.15 0 0.05" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="laser"/>
  </joint>

<!-- ======================================== Link  ================================================ -->
<!-- ==================================== arm definition =========================================== -->

  <link name="arm_base_link">
  	<inertial>
  		<mass value="0.1"/>
  		<origin xyz="0 0 0" rpy="0 0 0" />
  		<inertia ixx="0.0000416666667" ixy="0" ixz="0" iyy="0.0000416666667" iyz="0" izz="0.0000416666667"/>
  	</inertial>

  	<collision>
  	  <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.15"/>
      </geometry>
  	</collision>

  	<visual>
  	  <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.2"/>
      </geometry>
      <material name="white" />
  	</visual>

  </link>

<!-- ======================================== Joint  =============================================== -->



  <joint name="arm_base_to_base" type="fixed">
  	<origin rpy="0 0 0" xyz="0 0 0.085"/>
  	<parent link="base_link"/>
  	<child link="arm_base_link"/>
  </joint>

<!-- ======================================== Link  ================================================ -->

  <link name="arm_link_01">
  	<inertial>
  		<mass value="${arm_link_mass}"/>
  		<origin xyz="0 0 ${arm_link_01_lenght/2}" rpy="0 0 0" />
  		<inertia ixx="0.000010279" ixy="0" ixz="0" iyy="0.000010279" iyz="0" izz="0.000007225"/>
  	</inertial>

  	<collision>
  	  <origin xyz="0 0 ${arm_link_01_lenght/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.04" length="${arm_link_01_lenght}"/>
      </geometry>
  	</collision>

  	<visual>
  	  <origin xyz="0 0 ${arm_link_01_lenght/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.04" length="${arm_link_01_lenght}"/>
      </geometry>
      <material name="red" />
  	</visual>

  </link>

<!-- ======================================== Joint  =============================================== -->

  <joint name="arm_joint_01" type="revolute">
  	<axis xyz="0 0 1"/>
  	<limit effort="1000.0" lower="-3.14" upper="3.14" velocity="0.2"/>
  	<origin rpy="0 0 0" xyz="0 0 ${arm_link_01_lenght/2 -0.1}"/>
  	<parent link="arm_base_link"/>
  	<child link="arm_link_01"/>
  </joint>

<!-- ======================================== Link  ================================================ -->

    <link name="arm_link_02">
  	<inertial>
  		<mass value="${arm_link_mass}"/>
  		<origin xyz="0 0 ${arm_link_02_lenght/2}" rpy="0 0 0" />
  		<inertia ixx="0.000010279" ixy="0" ixz="0" iyy="0.000010279" iyz="0" izz="0.000007225"/>
  	</inertial>

  	<collision>
  	  <origin xyz="0 0 ${arm_link_02_lenght/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.04" length="${arm_link_02_lenght}"/>
      </geometry>
  	</collision>

  	<visual>
  	  <origin xyz="0 0 ${arm_link_02_lenght/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.04" length="${arm_link_02_lenght}"/>
      </geometry>
      <material name="red" />
  	</visual>

  </link>

<!-- ======================================== Joint  =============================================== -->

  <joint name="arm_joint_02" type="revolute">
  	<axis xyz="1 0 0"/>
  	<limit effort="1000.0" lower="-1.8" upper="1.8" velocity="0.2"/>
  	<origin rpy="0 0 0" xyz="0 0 ${arm_link_02_lenght/2}"/>
  	<parent link="arm_link_01"/>
  	<child link="arm_link_02"/>
  </joint>

<!-- ======================================== Link  ================================================ -->

      <link name="arm_link_03">
  	<inertial>
  		<mass value="${arm_link_mass}"/>
  		<origin xyz="0 0 ${arm_link_03_lenght/2}" rpy="0 0 0" />
  		<inertia ixx="0.000010279" ixy="0" ixz="0" iyy="0.000010279" iyz="0" izz="0.000007225"/>
  	</inertial>

  	<collision>
  	  <origin xyz="0 0 ${arm_link_03_lenght/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.04" length="${arm_link_03_lenght}"/>
      </geometry>
  	</collision>

  	<visual>
  	  <origin xyz="0 0 ${arm_link_03_lenght/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.04" length="${arm_link_03_lenght}"/>
      </geometry>
      <material name="red" />
  	</visual>

  </link>

<!-- ======================================== Joint  =============================================== -->

  <joint name="arm_joint_03" type="revolute">
  	<axis xyz="1 0 0"/>
  	<limit effort="1000.0" lower="-1.8" upper="1.8" velocity="0.2"/>
  	<origin rpy="0 0 0" xyz="0 0 ${arm_link_03_lenght/2}"/>
  	<parent link="arm_link_02"/>
  	<child link="arm_link_03"/>
  </joint>

<!-- ======================================== Link  ================================================ -->

    <link name="cluedo_link">
  	<inertial>
  		<mass value="0.025"/>
  		<origin xyz="0 0 ${cluedo_link_lenght/2}" rpy="0 0 0" />
  		<inertia ixx="0.000010279" ixy="0" ixz="0" iyy="0.000010279" iyz="0" izz="0.000007225"/>
  	</inertial>

  	<collision>
  	  <origin xyz="0 0 ${cluedo_link_lenght/2}" rpy="0 0 1.57"/>
      <geometry>
        <box size="0.034 0.2 0.08"/>
      </geometry>
  	</collision>

  	<visual>
  	  <origin xyz="0 0 ${cluedo_link_lenght/2}" rpy="0 0 1.57"/>
      <geometry>
        <box size="0.034 0.2 0.08"/>
      </geometry>
      <material name="red" />
  	</visual>

  </link>

<!-- ======================================== Joint  =============================================== -->

  <joint name="arm_joint_04" type="revolute">
  	<axis xyz="1 0 0"/>
  	<limit effort="1000.0" lower="-1.8" upper="1.8" velocity="0.5"/>
  	<origin rpy="0 0 0" xyz="0 0 ${cluedo_link_lenght/2}"/>
  	<parent link="arm_link_03"/>
  	<child link="cluedo_link"/>
  </joint>

<!-- ======================================== Link  ================================================ -->

<link name="right_grip_link">
  	<inertial>
  		<mass value="0.01"/>
  		<origin xyz="0 0 0" rpy="0 0 0" />
  		<inertia ixx="0.000010279" ixy="0" ixz="0" iyy="0.000010279" iyz="0" izz="0.000007225"/>
  	</inertial>

  	<collision>
  	  <origin xyz="-0.032 0.048 0.15" rpy="0 3.1415 -1.57"/>
      <geometry>
        <box size="0.06 0.02 0.08"/>
      </geometry>
  	</collision>

  	<visual>
  	  <origin xyz="-0.032 0.048 0.15" rpy="0 3.1415 -1.57"/>
      <geometry>
        <box size="0.06 0.02 0.08"/>
      </geometry>
      <material name="white" />
  	</visual>

  </link>

<!-- ======================================== Joint  =============================================== -->

  <joint name="right_grip_joint" type="prismatic">
  	<axis xyz="1 0 0"/>
  	<limit effort="1000.0" lower="-0.04" upper="0.035" velocity="6.5"/>
  	<origin rpy="0 0 0" xyz="-0.015 0 0.0"/>
  	<parent link="cluedo_link"/>
  	<child link="right_grip_link"/>
  </joint>


<!-- ======================================== Link  ================================================ -->

  <link name="left_grip_link">
  	<inertial>
  		<mass value="0.01"/>
  		<origin xyz="0 0 0" rpy="0 0 0" />
  		<inertia ixx="0.000010279" ixy="0" ixz="0" iyy="0.000010279" iyz="0" izz="0.000007225"/>
  	</inertial>

  	<collision>
  	  <origin xyz="0.06 0.048 0.15" rpy="0 3.1415 -1.57"/>
      <geometry>
        <box size="0.06 0.02 0.08"/>
      </geometry>
  	</collision>

  	<visual>
  	  <origin xyz="0.06 0.048 0.15" rpy="0 3.1415 -1.57"/>
      <geometry>
        <box size="0.06 0.02 0.08"/>
      </geometry>
      <material name="white" />
  	</visual>
  </link>

<!-- ======================================== Joint  =============================================== -->

  <joint name="left_grip_joint" type="prismatic">
  	<axis xyz="1 0 0"/>
  	<limit effort="1000.0" upper="0.04" lower="-0.035" velocity="6.5"/>
  	<origin rpy="0 0 0" xyz="-0.015 0 0.0"/>
  	<parent link="cluedo_link"/>
  	<child link="left_grip_link"/>
  </joint>

<!-- ===================================== Transmission  ============================================ -->



<transmission name="arm_joint_01_trans">
	<type>transmission_interface/SimpleTransmission</type>
	<joint name="arm_joint_01">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="motor1">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		<mechanicalInterface>1</mechanicalInterface>
	</actuator>
</transmission>

<transmission name="arm_joint_02_trans">
	<type>transmission_interface/SimpleTransmission</type>
	<joint name="arm_joint_02">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="motor2">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		<mechanicalInterface>1</mechanicalInterface>
	</actuator>
</transmission>

<transmission name="arm_joint_03_trans">
	<type>transmission_interface/SimpleTransmission</type>
	<joint name="arm_joint_03">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="motor3">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		<mechanicalInterface>1</mechanicalInterface>
	</actuator>
</transmission>

<transmission name="arm_joint_04_trans">
	<type>transmission_interface/SimpleTransmission</type>
	<joint name="arm_joint_04">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="motor4">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		<mechanicalInterface>1</mechanicalInterface>
	</actuator>
</transmission>

<transmission name="left_grip_trans">
	<type>transmission_interface/SimpleTransmission</type>
	<joint name="left_grip_joint">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="motor5">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		<mechanicalInterface>1</mechanicalInterface>
	</actuator>
</transmission>

<transmission name="right_grip_trans">
	<type>transmission_interface/SimpleTransmission</type>
	<joint name="right_grip_joint">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
	</joint>
	<actuator name="motor6">
		<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
		<mechanicalInterface>1</mechanicalInterface>
	</actuator>
</transmission>





</robot>
